### ISSUE TITLE
Missing keys.json

### ISSUE THREAD

**Issue by ModernMoGamer** [ruigouveiamaciel/sharex-custom-uploader#1]
Hello, I'm working towards installing this on my IIS Server.
I've run into an issue where I'm missing the keys.json and I've noticed it in your .gitignore I'm wondering where you got it, or how you should format it for use.

Thank you!

**Comment by SmOkEwOw** [comment]
there's a npm script called "createkey", i haven't used npm in a while but try "npm createkey" or "npm rum createkey"

**Comment by ruigouveiamaciel** [comment]
The issue has been solved. `npm start` should now create keys.json when it doesn't exist.
